<?php
use Application\Controller\CoreController;

?>
<!--begin::Bottom-->
<div class="header-bottom">
    <!--begin::Container-->
    <div class="container">
        <!--begin::Header Menu Wrapper-->
        <div class="header-navs header-navs-left" id="kt_header_navs">
            <!--begin::Tab Navs(for tablet and mobile modes)-->
            <ul class="header-tabs p-5 p-lg-0 d-flex d-lg-none nav nav-bold nav-tabs" role="tablist">
                <!--begin::Item-->
                <li class="nav-item mr-2">
                    <a href="#" class="nav-link btn btn-clean active" data-toggle="tab" data-target="#kt_header_tab_1" role="tab">Home</a>
                </li>
                <!--end::Item-->
                <?php
                foreach (array_keys($aIndexPermissions) as $sModule) {
                    $aInfo = $aIndexPermissions[$sModule];
                    if($aInfo['index']->show_in_menu != 1) {
                        continue;
                    }
                    # check if we are on active node
                    $sActive = ('/'.strtolower($this->sRouteName) == strtolower($aInfo['index']->nav_href)) ? ' active' : '';
                    # home is special case ..
                    $sActive = ($this->sRouteName == 'home' && $aInfo['index']->nav_href == '/') ? ' active' : $sActive;

                    $sIconName = substr($aInfo['index']->nav_href,1);

                    $bHasParam = stripos($sIconName,'?');
                    if($bHasParam === false) {

                    } else {
                        $sIconName = substr($sIconName,0,$bHasParam);
                    }
                    $sIcon = (array_key_exists($sIconName.'-icon',CoreController::$aGlobalSettings))
                        ?  CoreController::$aGlobalSettings[$sIconName.'-icon'] : '';
                ?>
                <!--begin::Item-->
                <li class="nav-item mr-2">
                    <a href="<?=$aInfo['index']->nav_href?>" class="nav-link btn btn-clean" data-toggle="tab" data-target="#kt_header_tab_2" role="tab">
                        <?=($sIcon != '') ? '<i class="'.$sIcon.'"></i> ' : ''?>
                        <?=$this->translate($aInfo['index']->nav_label)?>
                    </a>
                </li>
                <!--end::Item-->
                <?php } ?>
            </ul>
            <!--begin::Tab Navs-->
            <!--begin::Tab Content-->
            <div class="tab-content">
                <!--begin::Tab Pane-->
                <div class="tab-pane py-5 p-lg-0 <?=($this->layout()->sRouteName == 'app-home') ? 'show active' : ''?>" id="kt_header_tab_1">
                    <!--begin::Menu-->
                    <div id="kt_header_menu" class="header-menu header-menu-mobile header-menu-layout-default">
                        <!--begin::Nav-->
                        <ul class="menu-nav">
                            <li class="menu-item menu-item-active" aria-haspopup="true">
                                <a href="/home" class="menu-link">
                                    <span class="menu-text">Dashboard</span>
                                </a>
                            </li>
                        </ul>
                        <!--end::Nav-->
                    </div>
                    <!--end::Menu-->
                </div>
                <!--begin::Tab Pane-->
                <?php
                foreach (array_keys($aIndexPermissions) as $sModule) {
                $aInfo = $aIndexPermissions[$sModule];
                if($aInfo['index']->show_in_menu != 1) {
                    continue;
                }
                # check if we are on active node
                $sActive = ('/'.strtolower($this->sRouteName) == strtolower($aInfo['index']->nav_href)) ? ' active' : '';
                # home is special case ..
                $sActive = ($this->sRouteName == 'home' && $aInfo['index']->nav_href == '/') ? ' active' : $sActive;

                $sIconName = substr($aInfo['index']->nav_href,1);

                $bHasParam = stripos($sIconName,'?');
                if($bHasParam === false) {

                } else {
                    $sIconName = substr($sIconName,0,$bHasParam);
                }
                $sIcon = (array_key_exists($sIconName.'-icon',CoreController::$aGlobalSettings))
                    ?  CoreController::$aGlobalSettings[$sIconName.'-icon'] : '';
                ?>
                <!--begin::Tab Pane-->
                <div class="tab-pane p-5 p-lg-0 justify-content-between <?=('/'.$this->layout()->sRouteName == $aInfo['index']->nav_href) ? 'show active' : ''?>" id="kt_header_tab_<?=$sIconName?>">
                    <!--begin::Menu-->
                    <div id="kt_header_menu" class="header-menu header-menu-mobile header-menu-layout-default">
                        <!--begin::Nav-->
                        <ul class="menu-nav">
                            <li class="menu-item menu-item-active" aria-haspopup="true">
                                <a href="<?=$aInfo['index']->nav_href?>" class="menu-link">
                                    <span class="menu-text">
                                        <?=$this->translate('Overview')?>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <!--end::Nav-->
                    </div>
                    <!--end::Menu-->
                </div>
                <!--begin::Tab Pane-->
                <?php } ?>
            </div>
            <!--end::Tab Content-->
        </div>
        <!--end::Header Menu Wrapper-->
    </div>
    <!--end::Container-->
</div>
<!--end::Bottom-->
