<div class="subheader py-0 py-lg-6 subheader-transparent" id="kt_subheader">
    <div class="container d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <?php if(isset($this->layout()->aButtons)) { ?>
                <?php
                if(count($this->layout()->aButtons) > 0) {
                    foreach($this->layout()->aButtons as $oBtn) {
                        # Get current entity ID from layout
                        $iItemID = (isset($this->layout()->oItem)) ? $this->layout()->oItem->getID() : 0;

                        # Build final link for button
                        $sUrl = (isset($this->layout()->oItem->int_key)) ? $this->layout()->oItem->int_key : '';
                        $sFinalHref = str_replace(['##ID##','##URL##'],[$iItemID,$sUrl],$oBtn->href);
                        $bPrint = true;
                        if(isset($this->layout()->oItem)) {
                            if($oBtn->filter_check != '') {
                                $sFilter = $oBtn->filter_check;
                                if(property_exists($this->layout()->oItem,$sFilter)) {
                                    if($this->layout()->oItem->$sFilter != $oBtn->filter_value) {
                                        $bPrint = false;
                                    }
                                }
                            }
                        }

                        if($bPrint) {
                            ?>
                            <a href="<?= $sFinalHref ?>" class="btn btn-light-primary font-weight-bolder btn-sm"<?=($oBtn->mode == 'blank') ? ' target="_blank"' : ''?>>
                                <?= ($oBtn->icon != '') ? '<i class="' . $oBtn->icon . '"></i> ' : '' ?>
                                <?= $this->translate($oBtn->label) ?>
                            </a>
                            <?php
                        }
                    }
                }
                ?>
            <?php } ?>
            <!--begin::Actions-->
            <!--end::Actions-->
        </div>
        <!--end::Info-->
        <!--begin::Toolbar-->
        <div class="d-flex align-items-center">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item text-muted">
                        <a href="" class="text-muted">Pages</a>
                    </li>
                    <li class="breadcrumb-item text-muted">
                        <a href="" class="text-muted">Wizard 1</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Toolbar-->
    </div>
</div>